"""Add douyin crawl types.

Revision ID: 4b47062db094
Revises: fc4ecf252bbb
Create Date: 2026-02-23 22:44:57.354256

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b47062db094"
down_revision: Union[str, Sequence[str], None] = "fc4ecf252bbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Update crawltype enum to add douyin types
    op.execute("ALTER TYPE crawltype ADD VALUE 'douyin_hot'")
    op.execute("ALTER TYPE crawltype ADD VALUE 'douyin_search'")
    op.execute("ALTER TYPE crawltype ADD VALUE 'douyin_creators'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chapter_publishes_task_id"), table_name="chapter_publishes")
    op.drop_index(op.f("ix_crawl_results_task_id"), table_name="crawl_results")
    op.drop_index(op.f("ix_crawler_tasks_created_at"), table_name="crawler_tasks")
    op.drop_index(op.f("ix_crawler_tasks_platform_status"), table_name="crawler_tasks")
    op.drop_index(op.f("ix_platform_accounts_platform"), table_name="platform_accounts")
    op.drop_index(op.f("ix_publish_tasks_novel_id"), table_name="publish_tasks")
    op.drop_index(op.f("ix_publish_tasks_status"), table_name="publish_tasks")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_publish_tasks_status"), "publish_tasks", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_publish_tasks_novel_id"), "publish_tasks", ["novel_id"], unique=False
    )
    op.create_index(
        op.f("ix_platform_accounts_platform"),
        "platform_accounts",
        ["platform_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawler_tasks_platform_status"),
        "crawler_tasks",
        ["platform", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawler_tasks_created_at"),
        "crawler_tasks",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawl_results_task_id"),
        "crawl_results",
        ["crawler_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chapter_publishes_task_id"),
        "chapter_publishes",
        ["publish_task_id"],
        unique=False,
    )
    # ### end Alembic commands ###
