"""Add length_type column to novels

Revision ID: 575f1ce44645
Revises: b5dd1dd83814
Create Date: 2026-02-25 00:01:32.841331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "575f1ce44645"
down_revision: Union[str, Sequence[str], None] = "b5dd1dd83814"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 使用 IF EXISTS 避免表不存在时报错
    conn = op.get_bind()
    conn.execute(sa.text("DROP TABLE IF EXISTS crawl_results CASCADE"))
    conn.execute(sa.text("DROP TABLE IF EXISTS reader_preferences CASCADE"))
    conn.execute(sa.text("DROP TABLE IF EXISTS crawler_tasks CASCADE"))

    # Create the enum type first
    enum_type = sa.Enum("short", "medium", "long", name="novellengthtype")
    enum_type.create(op.get_bind(), checkfirst=True)

    # Then add the column with default value
    op.add_column(
        "novels",
        sa.Column("length_type", enum_type, nullable=False, server_default="medium"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("novels", "length_type")

    # Drop the enum type
    enum_type = sa.Enum("short", "medium", "long", name="novellengthtype")
    enum_type.drop(op.get_bind(), checkfirst=True)

    op.create_table(
        "crawler_tasks",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "task_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "platform", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "crawl_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="crawltaskstatus",
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "progress",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "result_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("crawler_tasks_pkey")),
    )
    op.create_table(
        "reader_preferences",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("genre", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "tags", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ranking_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "comment_sentiment",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "trend_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("data_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("crawler_task_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "book_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "book_title", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "author_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("word_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["crawler_task_id"],
            ["crawler_tasks.id"],
            name=op.f("reader_preferences_crawler_task_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reader_preferences_pkey")),
    )
    op.create_table(
        "crawl_results",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("crawler_task_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "platform", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "data_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "raw_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "processed_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["crawler_task_id"],
            ["crawler_tasks.id"],
            name=op.f("crawl_results_crawler_task_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("crawl_results_pkey")),
    )
    # ### end Alembic commands ###
