"""initial_tables

Revision ID: 5badc20e064a
Revises:
Create Date: 2026-02-22 18:38:44.671495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5badc20e064a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "novels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("genre", sa.String(length=50), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "planning", "writing", "completed", "published", name="novelstatus"
            ),
            nullable=True,
        ),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("chapter_count", sa.Integer(), nullable=True),
        sa.Column("cover_url", sa.String(length=500), nullable=True),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("target_platform", sa.String(length=50), nullable=True),
        sa.Column(
            "estimated_revenue", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("actual_revenue", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("token_cost", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reader_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("genre", sa.String(length=50), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "ranking_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "comment_sentiment", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("trend_score", sa.Float(), nullable=True),
        sa.Column("data_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chapters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("volume_number", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "reviewing", "published", name="chapterstatus"),
            nullable=True,
        ),
        sa.Column("outline", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("characters_appeared", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "plot_points", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "foreshadowing", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column(
            "continuity_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Novel chapters",
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "role_type",
            sa.Enum(
                "protagonist", "supporting", "antagonist", "minor", name="roletype"
            ),
            nullable=True,
        ),
        sa.Column(
            "gender", sa.Enum("male", "female", "other", name="gender"), nullable=True
        ),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("appearance", sa.Text(), nullable=True),
        sa.Column("personality", sa.Text(), nullable=True),
        sa.Column("background", sa.Text(), nullable=True),
        sa.Column("goals", sa.Text(), nullable=True),
        sa.Column("abilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "relationships", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("growth_arc", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("alive", "dead", "unknown", name="characterstatus"),
            nullable=True,
        ),
        sa.Column("first_appearance_chapter", sa.Integer(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generation_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum("planning", "writing", "editing", name="tasktype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="taskstatus",
            ),
            nullable=True,
        ),
        sa.Column("phase", sa.String(length=50), nullable=True),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "output_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("agent_logs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("token_usage", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plot_outlines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("structure_type", sa.String(length=50), nullable=True),
        sa.Column("volumes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("main_plot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sub_plots", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "key_turning_points", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("climax_chapter", sa.Integer(), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("novel_id"),
    )
    op.create_table(
        "world_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("world_name", sa.String(length=200), nullable=True),
        sa.Column("world_type", sa.String(length=50), nullable=True),
        sa.Column(
            "power_system", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("geography", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("factions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timeline", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "special_elements", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("novel_id"),
    )
    op.create_table(
        "token_usages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["task_id"], ["generation_tasks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_usages")
    op.drop_table("world_settings")
    op.drop_table("plot_outlines")
    op.drop_table("generation_tasks")
    op.drop_table("characters")
    op.drop_table("chapters")
    op.drop_table("reader_preferences")
    op.drop_table("novels")
    # ### end Alembic commands ###
