"""Change crawl_type from enum to string.

Revision ID: 82c931d1231a
Revises: 4b47062db094
Create Date: 2026-02-23 22:46:29.998793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "82c931d1231a"
down_revision: Union[str, Sequence[str], None] = "4b47062db094"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "crawler_tasks",
        "crawl_type",
        existing_type=postgresql.ENUM(
            "ranking", "trending_tags", "book_metadata", "genre_list", name="crawltype"
        ),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "crawler_tasks",
        "crawl_type",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "ranking", "trending_tags", "book_metadata", "genre_list", name="crawltype"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
