"""Add AI chat session models.

Revision ID: b5dd1dd83814
Revises: 186700edca0b
Create Date: 2026-02-24 16:05:24.092549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b5dd1dd83814"
down_revision: Union[str, Sequence[str], None] = "186700edca0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_chat_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("scene", sa.String(length=50), nullable=False),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_chat_sessions_scene"), "ai_chat_sessions", ["scene"], unique=False
    )
    op.create_index(
        op.f("ix_ai_chat_sessions_session_id"),
        "ai_chat_sessions",
        ["session_id"],
        unique=True,
    )
    op.create_table(
        "ai_chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["ai_chat_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_chat_messages_created_at"),
        "ai_chat_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_chat_messages_session_id"),
        "ai_chat_messages",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_chat_messages_session_id"), table_name="ai_chat_messages")
    op.drop_index(op.f("ix_ai_chat_messages_created_at"), table_name="ai_chat_messages")
    op.drop_table("ai_chat_messages")
    op.drop_index(op.f("ix_ai_chat_sessions_session_id"), table_name="ai_chat_sessions")
    op.drop_index(op.f("ix_ai_chat_sessions_scene"), table_name="ai_chat_sessions")
    op.drop_table("ai_chat_sessions")
    # ### end Alembic commands ###
