FROM m.daocloud.io/docker.io/node:20-alpine

WORKDIR /app

# 复制 package 文件
COPY frontend/package*.json ./

# 安装依赖
RUN npm install

# 复制前端代码
COPY frontend/ ./

# 复制并设置启动脚本权限
RUN chmod +x docker-entrypoint.sh

# 暴露端口
EXPOSE 3000

# 启动命令
CMD ["./docker-entrypoint.sh"]
