"""initial_schema_from_models.

Revision ID: 90162718523f
Revises:
Create Date: 2026-03-20 16:45:29.712750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "90162718523f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_chat_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("scene", sa.String(length=50), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_chat_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_chat_sessions_novel_id"), ["novel_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_chat_sessions_scene"), ["scene"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_chat_sessions_session_id"), ["session_id"], unique=True
        )

    op.create_table(
        "novels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("genre", sa.String(length=50), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("length_type", sa.String(length=50), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("chapter_count", sa.Integer(), nullable=True),
        sa.Column("cover_url", sa.String(length=500), nullable=True),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("target_platform", sa.String(length=50), nullable=True),
        sa.Column(
            "estimated_revenue", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("actual_revenue", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("token_cost", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column(
            "chapter_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "platform_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform_name", sa.String(length=50), nullable=False),
        sa.Column("account_name", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("encrypted_credentials", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["ai_chat_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_chat_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_chat_messages_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_chat_messages_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "chapters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("volume_number", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("outline", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("characters_appeared", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "plot_points", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "foreshadowing", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column(
            "continuity_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "detailed_outline", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "outline_task", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "outline_validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("outline_version", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Novel chapters",
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("role_type", sa.String(length=50), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("appearance", sa.Text(), nullable=True),
        sa.Column("personality", sa.Text(), nullable=True),
        sa.Column("background", sa.Text(), nullable=True),
        sa.Column("goals", sa.Text(), nullable=True),
        sa.Column("abilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "relationships", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("growth_arc", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("first_appearance_chapter", sa.Integer(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generation_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("phase", sa.String(length=50), nullable=True),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "output_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("agent_logs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("token_usage", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "novel_creation_flows",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("novel_id", sa.String(length=100), nullable=True),
        sa.Column("scene", sa.String(length=50), nullable=True),
        sa.Column("current_step", sa.String(length=50), nullable=True),
        sa.Column("genre", sa.String(length=100), nullable=True),
        sa.Column(
            "world_setting_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "synopsis_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("novel_title", sa.String(length=200), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("target_platform", sa.String(length=100), nullable=True),
        sa.Column("length_type", sa.String(length=50), nullable=True),
        sa.Column("selected_novel_id", sa.String(length=100), nullable=True),
        sa.Column("query_target", sa.String(length=100), nullable=True),
        sa.Column(
            "query_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("revision_target", sa.String(length=100), nullable=True),
        sa.Column(
            "revision_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("genre_confirmed", sa.Boolean(), nullable=True),
        sa.Column("world_setting_confirmed", sa.Boolean(), nullable=True),
        sa.Column("synopsis_confirmed", sa.Boolean(), nullable=True),
        sa.Column("final_confirmed", sa.Boolean(), nullable=True),
        sa.Column("revision_confirmed", sa.Boolean(), nullable=True),
        sa.Column(
            "conversation_history",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["ai_chat_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("novel_creation_flows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_novel_creation_flows_novel_id"), ["novel_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_novel_creation_flows_selected_novel_id"),
            ["selected_novel_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_novel_creation_flows_session_id"),
            ["session_id"],
            unique=True,
        )

    op.create_table(
        "plot_outlines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("structure_type", sa.String(length=50), nullable=True),
        sa.Column("volumes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("main_plot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "main_plot_detailed", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("sub_plots", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "key_turning_points", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("climax_chapter", sa.Integer(), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column(
            "update_history", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("novel_id"),
    )
    op.create_table(
        "publish_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("platform_account_id", sa.UUID(), nullable=False),
        sa.Column("publish_type", sa.String(length=50), nullable=False),
        sa.Column("target_chapters", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "result_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["platform_account_id"], ["platform_accounts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "world_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("world_name", sa.String(length=200), nullable=True),
        sa.Column("world_type", sa.String(length=50), nullable=True),
        sa.Column(
            "power_system", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("geography", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("factions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timeline", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "special_elements", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("novel_id"),
    )
    op.create_table(
        "agent_activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("agent_role", sa.String(length=200), nullable=True),
        sa.Column("activity_type", sa.String(length=50), nullable=False),
        sa.Column("phase", sa.String(length=50), nullable=True),
        sa.Column("step_number", sa.Integer(), nullable=True),
        sa.Column("iteration_number", sa.Integer(), nullable=True),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "output_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("raw_output", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["task_id"], ["generation_tasks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_activities", schema=None) as batch_op:
        batch_op.create_index(
            "idx_agent_activities_created", ["created_at"], unique=False
        )
        batch_op.create_index(
            "idx_agent_activities_novel_task", ["novel_id", "task_id"], unique=False
        )
        batch_op.create_index(
            "idx_agent_activities_type", ["activity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_activities_activity_type"),
            ["activity_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_agent_activities_agent_name"), ["agent_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_activities_novel_id"), ["novel_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_activities_task_id"), ["task_id"], unique=False
        )

    op.create_table(
        "chapter_publishes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("publish_task_id", sa.UUID(), nullable=False),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("platform_chapter_id", sa.String(length=100), nullable=True),
        sa.Column("platform_url", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["publish_task_id"], ["publish_tasks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "character_name_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("old_name", sa.String(length=100), nullable=False),
        sa.Column("new_name", sa.String(length=100), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("changed_by", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "token_usages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["task_id"], ["generation_tasks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # 手动添加：角色名字唯一索引（基于 lower(name) 的 functional index，autogenerate 无法检测）
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX ix_characters_novel_id_name_unique "
            "ON characters (novel_id, lower(name))"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_usages")
    op.drop_table("character_name_versions")
    op.drop_table("chapter_publishes")
    with op.batch_alter_table("agent_activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_activities_task_id"))
        batch_op.drop_index(batch_op.f("ix_agent_activities_novel_id"))
        batch_op.drop_index(batch_op.f("ix_agent_activities_agent_name"))
        batch_op.drop_index(batch_op.f("ix_agent_activities_activity_type"))
        batch_op.drop_index("idx_agent_activities_type")
        batch_op.drop_index("idx_agent_activities_novel_task")
        batch_op.drop_index("idx_agent_activities_created")

    op.drop_table("agent_activities")
    op.drop_table("world_settings")
    op.drop_table("publish_tasks")
    op.drop_table("plot_outlines")
    with op.batch_alter_table("novel_creation_flows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_novel_creation_flows_session_id"))
        batch_op.drop_index(batch_op.f("ix_novel_creation_flows_selected_novel_id"))
        batch_op.drop_index(batch_op.f("ix_novel_creation_flows_novel_id"))

    op.drop_table("novel_creation_flows")
    op.drop_table("generation_tasks")
    op.drop_table("characters")
    op.drop_table("chapters")
    with op.batch_alter_table("ai_chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_chat_messages_session_id"))
        batch_op.drop_index(batch_op.f("ix_ai_chat_messages_created_at"))

    op.drop_table("ai_chat_messages")
    op.drop_table("platform_accounts")
    op.drop_table("novels")
    with op.batch_alter_table("ai_chat_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_chat_sessions_session_id"))
        batch_op.drop_index(batch_op.f("ix_ai_chat_sessions_scene"))
        batch_op.drop_index(batch_op.f("ix_ai_chat_sessions_novel_id"))

    op.drop_table("ai_chat_sessions")
    # ### end Alembic commands ###
